### ISSUE TITLE
Add Erlang as static PIE build

### ISSUE THREAD

**Issue by razvand** [unikraft/static-pie-apps#23]
Add [Erlang](https://www.erlang.org/) as a `-static-pie` build. Test it natively on Linux and with [run-elfloader](https://github.com/unikraft/run-app-elfloader) on Unikraft. In case of issues with Unikraft, post an issue in the [Unikraft core repository](https://github.com/unikraft/unikraft).

Follow the structure of [existing applications](https://github.com/unikraft/static-pie-apps) or [submitted for review applications](https://github.com/unikraft/static-pie-apps/pulls): create a folder with `build.sh` script, a `README.md` file, a `rootfs/` subfolder (if required), the `-static-pie` built executable and other useful files.

**Hackathon points**: 50

**Comment by salameme** [comment]
Working on this

**Comment by salameme** [comment]
Erlang otp https://github.com/erlang/otp, can't compile statically as `erlc` doesn't support static linking.

Reproduce with:
```console
$ CFLAGS='-O2 -g -fPIE -static' CXXFLAGS='-O2 -g -fPIE -static' LDFLAGS='-static' ./configure --without-termcap --without-javac --without-ssl --enable-pie
...
$ make
...
  ERLC   ../ebin/leex.beam
dlsym: No such file or directory
...
```

**Comment by razvand** [comment]
10 points awarded
